
/**
* EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* mercredi 15 octobre 2014 10 h 49 CEST
*/

public interface EchoOperations 
{
  String echoString (String mesg);
} // interface EchoOperations
