
/**
* Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* mercredi 15 octobre 2014 10 h 49 CEST
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
