/* calcClient.c
   Generated by gSOAP 2.8.18 from calc.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "calcH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) calcClient.c ver 2.8.18 2014-10-29 09:08:01 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_calc__add(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double *result)
{	struct calc__add soap_tmp_calc__add;
	struct calc__addResponse *soap_tmp_calc__addResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:18083/calc/";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_calc__add.a = a;
	soap_tmp_calc__add.b = b;
	soap_serializeheader(soap);
	soap_serialize_calc__add(soap, &soap_tmp_calc__add);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_calc__add(soap, &soap_tmp_calc__add, "calc:add", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_calc__add(soap, &soap_tmp_calc__add, "calc:add", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_double(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_calc__addResponse = soap_get_calc__addResponse(soap, NULL, "calc:addResponse", NULL);
	if (!soap_tmp_calc__addResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_calc__addResponse->result)
		*result = *soap_tmp_calc__addResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_calc__sub(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double *result)
{	struct calc__sub soap_tmp_calc__sub;
	struct calc__subResponse *soap_tmp_calc__subResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:18083/calc/";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_calc__sub.a = a;
	soap_tmp_calc__sub.b = b;
	soap_serializeheader(soap);
	soap_serialize_calc__sub(soap, &soap_tmp_calc__sub);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_calc__sub(soap, &soap_tmp_calc__sub, "calc:sub", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_calc__sub(soap, &soap_tmp_calc__sub, "calc:sub", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_double(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_calc__subResponse = soap_get_calc__subResponse(soap, NULL, "calc:subResponse", NULL);
	if (!soap_tmp_calc__subResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_calc__subResponse->result)
		*result = *soap_tmp_calc__subResponse->result;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of calcClient.c */
