
/**
* AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mercredi 15 octobre 2014 11 h 14 CEST
*/

public interface AccountOperations 
{
  void deposit (int amount);
  void withdraw (int amount);
  int balance ();
} // interface AccountOperations
