
/**
* Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mercredi 15 octobre 2014 11 h 14 CEST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
