
/**
* BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* mercredi 15 octobre 2014 11 h 14 CEST
*/

public interface BankOperations 
{
  Account create ();
  void destroy (Account a);
} // interface BankOperations
